/**
 * Client-side triage — 3-layer pipeline, distilled from the BMC-trained corpus.
 *
 * GitHub Pages has no Python service or Docker runner, so the site ships the
 * *distilled lexicon* (site/src/lib/data/triage_lexicon.json) generated by
 * ml/export_bmc_lexicon.py. The pipeline mirrors the main app exactly:
 *
 *   L1  distilled BMC lexicon (trained salience weights, held-out eval in metrics)
 *   L2  hand-written Mumbai keyword rules (Hinglish + MCGM jargon)
 *   L3  manual review (no keyword evidence anywhere)
 *
 * Every layer records which layer decided — same transparency contract as the
 * Python pipeline in the main repo.
 */
import lexicon from "./data/triage_lexicon.json";

export type Priority = "urgent" | "high" | "medium" | "low";

export type TriageResult = {
  category: string;
  priority: Priority;
  department: string;
  confidence: number;
  sourceLayer: "lexicon" | "rules" | "manual";
  /** Matched tokens with their salience — the explainability panel. */
  signals: { word: string; salience: number }[];
  summary: string;
};

export const CATEGORIES = lexicon.categories as string[];
export const LEXICON_METRICS = lexicon.metrics;

export const DEPARTMENT_MAP = lexicon.department as Record<string, string>;

export function departmentFor(cat: string): string {
  return DEPARTMENT_MAP[cat] ?? "Ward Office (General)";
}

export function slaHoursFor(cat: string, priority: Priority): number {
  const catH = (lexicon.categorySlaHours as Record<string, number>)[cat];
  return catH ?? (lexicon.slaHours as Record<string, number>)[priority] ?? 168;
}

function tokenize(text: string): Set<string> {
  const toks = text.toLowerCase().match(/[a-z]+/g) ?? [];
  return new Set(toks);
}

/** L1 — distilled BMC lexicon scoring (salience-weighted votes). */
function classifyLexicon(text: string): TriageResult | null {
  const toks = tokenize(text);
  const lexicons = lexicon.lexicons as Record<string, { w: string; s: number }[]>;
  let best: { cat: string; score: number; hits: { word: string; salience: number }[] } | null = null;

  for (const [cat, entries] of Object.entries(lexicons)) {
    const hits = entries.filter((e) => toks.has(e.w));
    if (!hits.length) continue;
    const score = hits.reduce((a, e) => a + e.s, 0);
    if (!best || score > best.score) {
      best = { cat, score, hits: hits.map((h) => ({ word: h.w, salience: h.s })) };
    }
  }
  if (!best) return null;

  return {
    category: best.cat,
    priority: "medium",
    department: departmentFor(best.cat),
    confidence: Math.min(0.93, 0.5 + best.score * 0.06),
    sourceLayer: "lexicon",
    signals: best.hits.sort((a, b) => b.salience - a.salience).slice(0, 5),
    summary: "",
  };
}

const URGENT = (lexicon.priority.urgent as string[]);
const HIGH = (lexicon.priority.high as string[]);
const LOW = (lexicon.priority.low as string[]);

function classifyPriority(text: string, fallback: Priority): Priority {
  const t = text.toLowerCase();
  if (URGENT.some((w) => t.includes(w))) return "urgent";
  if (HIGH.some((w) => t.includes(w))) return "high";
  if (LOW.some(Lw => t.includes(Lw))) return "low";
  return fallback;
}

/** L2 — hand rules (also the summary/category fallback). */
const RULES: { cat: string; kws: string[] }[] = [
  { cat: "Pothole", kws: ["pothole", "gaddha", "crater", "road defect", "road surface", "tar road", "broken road"] },
  { cat: "Drainage", kws: ["drain", "nali", "waterlog", "water log", "flood", "catchpit", "silt", "desilt", "storm water"] },
  { cat: "Waste", kws: ["garbage", "kachra", "trash", "waste", "litter", "dumping", "bin", "sanitation"] },
  { cat: "Water", kws: ["water supply", "no water", "pipeline burst", "water leak", "contaminated", "pressure", "valve", "paani nahi"] },
  { cat: "Streetlight", kws: ["streetlight", "street light", "lamp post", "unlit", "dark street", "light pole", "bijli"] },
  { cat: "Sewage", kws: ["sewage", "sewer", "manhole", "ganda paani", "suction", "chamber", "overflow"] },
  { cat: "Graffiti", kws: ["graffiti", "banner", "flex", "poster", "defaced", "spray paint", "sticker"] },
  { cat: "Other", kws: ["stray dog", "encroachment", "abandoned vehicle", "tree branch", "parking", "footpath", "noise"] },
];

function classifyRules(text: string): TriageResult | null {
  const t = text.toLowerCase();
  let best: { cat: string; hits: string[] } | null = null;
  for (const rule of RULES) {
    const hits = rule.kws.filter((k) => t.includes(k));
    if (hits.length && (!best || hits.length > best.hits.length)) {
      best = { cat: rule.cat, hits };
    }
  }
  if (!best) return null;
  return {
    category: best.cat,
    priority: "medium",
    department: departmentFor(best.cat),
    confidence: Math.min(0.8, 0.45 + best.hits.length * 0.08),
    sourceLayer: "rules",
    signals: best.hits.map((w) => ({ word: w, salience: 1 })),
    summary: "",
  };
}

function summarize(raw: string): string {
  const first = raw.split(/(?<=[.!?])\s|\n/)[0] ?? raw;
  return first.length > 140 ? `${first.slice(0, 137)}…` : first || "Complaint received.";
}

/** Public API — classify raw citizen text. Never throws. */
export function classify(text: string): TriageResult {
  const safe = String(text ?? "").trim();
  if (!safe) {
    return {
      category: "Other",
      priority: "medium",
      department: departmentFor("Other"),
      confidence: 0.15,
      sourceLayer: "manual",
      signals: [],
      summary: "Empty complaint — manual review.",
    };
  }
  const l1 = classifyLexicon(safe);
  const l2 = l1 ?? classifyRules(safe);
  if (l2) {
    return { ...l2, priority: classifyPriority(safe, l2.priority), summary: summarize(safe) };
  }
  // L3 — no signal anywhere
  return {
    category: "Other",
    priority: "medium",
    department: departmentFor("Other"),
    confidence: 0.25,
    sourceLayer: "manual",
    signals: [],
    summary: summarize(safe),
  };
}

/** Lightweight photo triage — same input contract as the CNN in the main app. */
export type VisionPreview = {
  ok: boolean;
  reason?: string;
  category: string | null;
  confidence: number;
  severity: number;
  note: string;
};

export async function analyzePhoto(file: File): Promise<VisionPreview> {
  try {
    if (typeof document === "undefined") throw new Error("no_dom");
    const bmp = await createImageBitmap(file);
    const w = (bmp.width / 4) | 0;
    const h = (bmp.height / 4) | 0;
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d", { willReadFrequently: true });
    if (!ctx) throw new Error("no_canvas");
    ctx.drawImage(bmp, 0, 0, w, h);
    const d = ctx.getImageData(0, 0, w, h).data;
    let dark = 0;
    let edge = 0;
    let grayPrev = 0;
    for (let i = 0; i < w * h; i++) {
      const g = (0.299 * d[i * 4] + 0.587 * d[i * 4 + 1] + 0.114 * d[i * 4 + 2]) / 255;
      if (i > 0) edge += Math.abs(g - grayPrev);
      grayPrev = g;
      if (g < 0.28) dark++;
    }
    const px = w * h;
    const darkFrac = dark / px;
    const edgeEnergy = edge / px;
    const severity = Math.max(0, Math.min(1, darkFrac * 1.6 + edgeEnergy * 1.4));
    return {
      ok: true,
      category: null, // honest: the CNN weights are too heavy for a static site; text triage leads
      confidence: Math.min(0.9, 0.5 + severity * 0.4),
      severity,
      note:
        severity > 0.55
          ? "High-detail damage signature — severity boosted"
          : "Photo accepted; text triage leads classification",
    };
  } catch {
    return { ok: false, reason: "decode_failed", category: null, confidence: 0, severity: 0, note: "Photo could not be decoded — text triage continues." };
  }
}
