/**
 * CivicLens CNN — TypeScript inference (from-scratch, mirrors ml/train_cnn.py).
 *
 * The same 3-conv + dense trunk trained in NumPy also runs here in pure TS,
 * loading the exported weights (src/lib/vision/cnn_weights.json, generated by
 * ml/export_cnn_ts.py). Parity is asserted by ml/export_cnn_ts.py's probe and
 * src/lib/vision/parity.test.ts.
 *
 * Input: 48×48 grayscale [0,1] — the caller decodes/resizes the photo.
 * Output: 8-way category softmax + a 0-1 image-severity estimate from the
 * second head. Never throws: corrupt/missing weights degrade to null and the
 * caller falls back (same policy as the rest of the pipeline).
 */
import rawWeights from "./cnn_weights.json";

export const CNN_CATEGORIES: string[] = rawWeights.categories;
export const CNN_METRICS = rawWeights.metrics;

const IMG_H = rawWeights.input.height; // 48
const IMG_W = rawWeights.input.width; // 48

export type CnnResult = {
  category: string;
  confidence: number;
  /** 0-1 estimated degradation from the severity head. */
  severity: number;
  /** Top-5 category probabilities (sorted desc). */
  probabilities: { category: string; p: number }[];
  sourceLayer: "cnn_ts" | "cnn_service";
};

// ---------------------------------------------------------------------------
// Weight materialization — flat arrays -> typed JS number arrays
// ---------------------------------------------------------------------------

type ConvLayer = {
  /** (out, in, 3, 3) flattened -> indexed o*in*9 + c*9 + k. */
  W: Float64Array;
  b: Float64Array;
  outC: number;
  inC: number;
};

function convLayer(spec: { W: number[]; b: number[]; in: number; out: number }): ConvLayer {
  return {
    W: new Float64Array(spec.W),
    b: new Float64Array(spec.b),
    outC: spec.out,
    inC: spec.in,
  };
}

const CONV: ConvLayer[] = rawWeights.conv.map(convLayer);
const DENSE_W = new Float64Array(rawWeights.dense.W); // (out=64, in=600)
const DENSE_B = new Float64Array(rawWeights.dense.b);
const CLS_W = new Float64Array(rawWeights.classifier.W); // (out=8, in=64)
const CLS_B = new Float64Array(rawWeights.classifier.b);
const SEV_W = new Float64Array(rawWeights.severity_head.W); // (1, 64)
const SEV_B = new Float64Array(rawWeights.severity_head.b);

const FLAT_LEN = rawWeights.dense.in; // 24*5*5 = 600

// ---------------------------------------------------------------------------
// Ops (valid 3×3 conv, 2×2 max-pool with odd-dim zero-pad, ReLU, softmax)
// ---------------------------------------------------------------------------

function conv2d(x: Float64Array, c: number, h: number, w: number, layer: ConvLayer): { out: Float64Array; h: number; w: number } {
  const oh = h - 2;
  const ow = w - 2;
  const out = new Float64Array(layer.outC * oh * ow);
  const { W, b, outC, inC } = layer;
  for (let o = 0; o < outC; o++) {
    const wBase = o * inC * 9;
    for (let ch = 0; ch < inC; ch++) {
      const wK = wBase + ch * 9;
      const xCh = ch * h * w;
      for (let i = 0; i < oh; i++) {
        for (let j = 0; j < ow; j++) {
          let sum = 0;
          for (let di = 0; di < 3; di++) {
            const xr = xCh + (i + di) * w + j;
            const wr = wK + di * 3;
            sum += W[wr] * x[xr] + W[wr + 1] * x[xr + 1] + W[wr + 2] * x[xr + 2];
          }
          out[o * oh * ow + i * ow + j] += sum;
        }
      }
    }
    const ob = o * oh * ow;
    for (let i = 0; i < oh * ow; i++) out[ob + i] += b[o];
  }
  return { out, h: oh, w: ow };
}

function reluInPlace(v: Float64Array): void {
  for (let i = 0; i < v.length; i++) if (v[i] < 0) v[i] = 0;
}

function maxpool2(x: Float64Array, c: number, h: number, w: number): { out: Float64Array; h: number; w: number } {
  const ph = h % 2;
  const pw = w % 2;
  const H = h + ph;
  const W = w + pw;
  const oh = H >> 1;
  const ow = W >> 1;
  const out = new Float64Array(c * oh * ow);
  for (let ch = 0; ch < c; ch++) {
    for (let i = 0; i < oh; i++) {
      for (let j = 0; j < ow; j++) {
        const r0 = (2 * i) * w + ch * h * w;
        const r1 = Math.min(2 * i + 1, h - 1) * w + ch * h * w;
        const c0 = 2 * j;
        const c1 = Math.min(2 * j + 1, w - 1);
        const a = x[r0 + c0];
        const b2 = x[r0 + c1];
        const d = x[r1 + c0];
        const e = x[r1 + c1];
        out[ch * oh * ow + i * ow + j] = Math.max(a, b2, d, e);
      }
    }
  }
  return { out, h: oh, w: ow };
}

function softmax(v: number[]): number[] {
  const max = Math.max(...v);
  const e = v.map((x) => Math.exp(x - max));
  const s = e.reduce((a, b) => a + b, 0);
  return e.map((x) => x / s);
}

// ---------------------------------------------------------------------------
// Forward pass — input layout: channel-major (ch*H*W + i*W + j), same as NumPy
// ---------------------------------------------------------------------------

export function cnnForward(x48: Float64Array): CnnResult {
  let cur = x48;
  let c = 1;
  let h = IMG_H;
  let w = IMG_W;

  for (const layer of CONV) {
    const conv = conv2d(cur, c, h, w, layer);
    reluInPlace(conv.out);
    const pooled = maxpool2(conv.out, layer.outC, conv.h, conv.w);
    cur = pooled.out;
    c = layer.outC;
    h = pooled.h;
    w = pooled.w;
  }

  // Flatten channel-major (matches NumPy reshape).
  const flat = cur; // already (c, h, w) channel-major
  const denseIn = new Float64Array(FLAT_LEN);
  denseIn.set(flat.subarray(0, Math.min(FLAT_LEN, flat.length)));

  const dense = new Float64Array(DENSE_B);
  for (let o = 0; o < DENSE_B.length; o++) {
    const wr = o * FLAT_LEN;
    let sum = DENSE_B[o];
    for (let i = 0; i < FLAT_LEN; i++) sum += DENSE_W[wr + i] * denseIn[i];
    dense[o] = sum;
  }
  for (let i = 0; i < dense.length; i++) if (dense[i] < 0) dense[i] = 0; // ReLU

  const logits: number[] = [];
  for (let o = 0; o < CLS_B.length; o++) {
    const wr = o * DENSE_B.length;
    let sum = CLS_B[o];
    for (let i = 0; i < DENSE_B.length; i++) sum += CLS_W[wr + i] * dense[i];
    logits.push(sum);
  }
  const probsArr = softmax(logits);

  let sev = SEV_B[0];
  for (let i = 0; i < DENSE_B.length; i++) sev += SEV_W[i] * dense[i];
  sev = Math.max(0, Math.min(1, sev));

  const order = probsArr.map((p, i) => ({ p, i })).sort((a, b) => b.p - a.p);
  return {
    category: CNN_CATEGORIES[order[0].i] ?? "Other",
    confidence: order[0].p,
    severity: sev,
    probabilities: order.slice(0, 5).map((o) => ({
      category: CNN_CATEGORIES[o.i] ?? `class_${o.i}`,
      p: o.p,
    })),
    sourceLayer: "cnn_ts",
  };
}

/**
 * Convenience: mean-pool/downscale an arbitrary grayscale raster to 48×48.
 * `pixels` is row-major in [0,1]. Robust to any input size.
 */
export function toTensor48(pixels: Float64Array, w: number, h: number): Float64Array {
  const out = new Float64Array(IMG_H * IMG_W);
  for (let i = 0; i < IMG_H; i++) {
    const sy = Math.min(h - 1, Math.floor((i * h) / IMG_H));
    for (let j = 0; j < IMG_W; j++) {
      const sx = Math.min(w - 1, Math.floor((j * w) / IMG_W));
      out[i * IMG_W + j] = pixels[sy * w + sx];
    }
  }
  return out;
}
