/**
 * Civic Incident Neural Network — TypeScript inference.
 *
 * The same MLP trained in ml/train_nn.py (NumPy, no frameworks) also runs
 * here in pure TypeScript. The weights JSON is generated by the training
 * script; a round-trip assert in train_nn.py guarantees logit parity with
 * NumPy (atol 1e-6), so both runtimes are provably equivalent.
 *
 * Two independent predictors, shown side by side in the UI (a defensible
 * comparison — not "the NN is automatically better"):
 *   1. neural      — 10 → 32 → 16 → 8 → 4 MLP over engineered features
 *   2. rule_base   — the hand-written monotone score the NN was trained to beat
 *
 * Fallback layers for the risk head (like the rest of the pipeline):
 *   NN weights → rule baseline → default LOW. Never throws.
 */
import rawWeights from "./weights.json";

import {
  buildRiskFeatures,
  RISK_FEATURE_LABELS,
  RISK_LEVELS,
  type RiskFeatureInput,
} from "./features";

type WeightsFile = {
  version: number;
  architecture: number[];
  risk_levels: string[];
  feature_order: string[];
  metrics: {
    nn_accuracy: number;
    nn_macro_f1: number;
    rule_baseline_accuracy: number;
  };
  layers: { W: number[][]; b: number[] }[];
};

const W = rawWeights as WeightsFile;

export const NN_METRICS = W.metrics;
export const NN_ARCHITECTURE = W.architecture;
const RISK_LEVELS_MODEL = W.risk_levels as string[];

/** Re-exports used by the UI. */
export { RISK_FEATURE_LABELS, RISK_LEVELS };

type RiskLevel = (typeof RISK_LEVELS)[number];

export type RiskPrediction = {
  level: RiskLevel;
  probabilities: { level: RiskLevel; p: number }[];
  /** Raw layer activations — feeds the live network diagram. */
  activations: {
    input: number[];
    hidden1: number[];
    hidden2: number[];
    hidden3: number[];
    output: number[];
  };
  /** Top contributing input features for the chosen class. */
  topSignals: { feature: string; label: string; value: number }[];
  /** Which layer produced this prediction — shown for transparency. */
  sourceLayer: "neural_net" | "rule_baseline";
  /** The rule baseline's answer, for the "NN vs rules" comparison. */
  baselineLevel: RiskLevel;
};

// ---------------------------------------------------------------------------
// Forward pass — mirrors ml/train_nn.py::forward / softmax
// ---------------------------------------------------------------------------

function matVec(x: number[], Wm: number[][], b: number[]): number[] {
  const out = new Array<number>(b.length);
  for (let j = 0; j < b.length; j++) {
    let sum = b[j];
    const row = Wm[j];
    for (let k = 0; k < row.length; k++) sum += row[k] * x[k];
    out[j] = sum;
  }
  return out;
}

function relu(v: number[]): number[] {
  return v.map((x) => (x > 0 ? x : 0));
}

function softmax(v: number[]): number[] {
  const max = Math.max(...v);
  const e = v.map((x) => Math.exp(x - max));
  const sum = e.reduce((a, b) => a + b, 0);
  return e.map((x) => x / sum);
}

function argmax(v: number[]): number {
  let best = 0;
  for (let i = 1; i < v.length; i++) if (v[i] > v[best]) best = i;
  return best;
}

// ---------------------------------------------------------------------------
// Rule baseline — mirrors ml/train_nn.py::rule_baseline
// ---------------------------------------------------------------------------

/**
 * Hand-written monotone score. This is the honest "before" that judges can
 * compare the NN against: same inputs, no learning, just expert weights.
 */
export function ruleBaseline(x: number[]): { level: RiskLevel; score: number } {
  // x layout: [vol, accel, sev, evidence, accidents, rain, traffic, hist, dist, tod]
  const vol = x[0];
  const accel = x[1];
  const sev = x[2];
  const ev = x[3];
  const acc = x[4];
  const rain = x[5];
  const hist = x[7];
  const prox = 1 - x[8]; // normalized distance: closer = riskier
  const score =
    0.3 * vol +
    0.25 * accel +
    0.2 * sev +
    0.1 * ev +
    0.1 * hist +
    0.05 * rain +
    0.05 * prox * (acc > 0.2 ? 1 : 0);
  const idx = score < 0.36 ? 0 : score < 0.54 ? 1 : score < 0.74 ? 2 : 3;
  return { level: RISK_LEVELS[idx], score };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

function forwardAll(x: number[]) {
  const z1 = matVec(x, W.layers[0].W, W.layers[0].b);
  const a1 = relu(z1);
  const z2 = matVec(a1, W.layers[1].W, W.layers[1].b);
  const a2 = relu(z2);
  const z3 = matVec(a2, W.layers[2].W, W.layers[2].b);
  const a3 = relu(z3);
  const z4 = matVec(a3, W.layers[3].W, W.layers[3].b);
  return { a1, a2, a3, z4 };
}

/**
 * Gradient-free attribution: how strongly each input feature pushes toward
 * the chosen class, computed as a through-layer path product (input weight ×
 * ReLU mask × output weight). Cheap, deterministic, good enough to rank
 * signals — the exact numbers are shown, the method is documented.
 */
function topSignalsFor(
  x: number[],
  a1: number[],
  chosenClass: number
): { feature: string; label: string; value: number }[] {
  const outW = W.layers[3].W[chosenClass] ?? [];
  const strengths = x.map((_, i) => {
    let s = 0;
    for (let j = 0; j < a1.length; j++) {
      const w1 = W.layers[0].W[j]?.[i] ?? 0;
      s += outW[j] * (a1[j] > 0 ? 1 : 0) * w1;
    }
    return s;
  });
  const keys = Object.keys(RISK_FEATURE_LABELS) as (keyof typeof RISK_FEATURE_LABELS)[];
  return strengths
    .map((s, i) => ({
      feature: W.feature_order[i] ?? `feature_${i}`,
      label: RISK_FEATURE_LABELS[keys[i]] ?? W.feature_order[i] ?? `feature_${i}`,
      value: s,
    }))
    .sort((a, b) => b.value - a.value)
    .slice(0, 3);
}

/**
 * Run the Civic Incident Neural Network on engineered features.
 * Never throws: stale/corrupt weights fall back to the rule baseline and the
 * UI labels which layer decided.
 */
export function predictRisk(input: RiskFeatureInput): RiskPrediction {
  const x = buildRiskFeatures(input);
  const baseline = ruleBaseline(x);

  const layersOk =
    W.layers?.length === 4 &&
    W.architecture?.length === 5 &&
    W.layers.every((l) => Array.isArray(l.W) && Array.isArray(l.b));

  if (!layersOk) {
    return {
      level: baseline.level,
      probabilities: RISK_LEVELS.map((lvl, i) => ({
        level: lvl,
        p: lvl === baseline.level ? 1 : 0,
      })),
      activations: { input: x, hidden1: [], hidden2: [], hidden3: [], output: [] },
      topSignals: [],
      sourceLayer: "rule_baseline",
      baselineLevel: baseline.level,
    };
  }

  const { a1, a2, a3, z4 } = forwardAll(x);
  const probs = softmax(z4);
  const best = argmax(z4);

  return {
    level: RISK_LEVELS_MODEL[best] as RiskLevel,
    probabilities: RISK_LEVELS.map((lvl, i) => ({ level: lvl, p: probs[i] })),
    activations: { input: x, hidden1: a1, hidden2: a2, hidden3: a3, output: z4 },
    topSignals: topSignalsFor(x, a1, best),
    sourceLayer: "neural_net",
    baselineLevel: baseline.level,
  };
}
