import { Link } from "react-router-dom";
import { SectionHead, Chip, Meter } from "../components/Reveal";
import { useTickets } from "../state";
import { slaState } from "../lib/tickets";

type Mode = "map" | "risk" | "insights" | "channels";

export default function Operations({ mode }: { mode: Mode }) {
  const { tickets } = useTickets();
  const open = tickets.filter((ticket) => ticket.status !== "verified");
  const urgent = open.filter((ticket) => ticket.priority === "urgent" || ticket.priority === "high");
  const onTime = tickets.filter((ticket) => !slaState(ticket).breached).length;
  const categories = [...new Set(tickets.map((ticket) => ticket.category))];

  const headings: Record<Mode, { eyebrow: string; title: string; sub: string }> = {
    map: { eyebrow: "Spatial intelligence", title: "Live complaint map", sub: "Every report is placed into a neutral ward context so citizens and operations teams can see where service attention is concentrated." },
    risk: { eyebrow: "Civic Incident NN", title: "Risk engine", sub: "Risk is calculated from priority, complaint density, category severity, SLA pressure and evidence signals." },
    insights: { eyebrow: "Evidence ledger", title: "Insights from the queue", sub: "Calculated from the current ticket store: no invented totals and no opaque scorecards." },
    channels: { eyebrow: "Signal intake", title: "Signal channels", sub: "Bring reports in through citizen text, photos and monitored signal adapters, then send every item through the same triage pipeline." },
  };

  return <div className="mx-auto max-w-6xl px-4 py-14"><SectionHead {...headings[mode]} />
    {mode === "map" && <section className="well overflow-hidden p-4"><div className="relative min-h-[440px] overflow-hidden rounded-xl bg-[#d9ece7]" style={{ backgroundImage: "linear-gradient(rgba(13,33,41,.08) 1px, transparent 1px), linear-gradient(90deg, rgba(13,33,41,.08) 1px, transparent 1px)", backgroundSize: "42px 42px" }}><div className="absolute inset-[12%] rounded-[42%] border-2 border-tide-400/50 bg-tide-100/40" /><div className="absolute inset-[28%_18%_18%_35%] rounded-[48%] border-2 border-saffron-400/60 bg-saffron-100/30" />{tickets.map((ticket, index) => <button key={ticket.id} type="button" title={`${ticket.category}: ${ticket.location}`} className="absolute grid h-9 w-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-white text-xs font-black text-white shadow-lg" style={{ left: `${18 + ((index * 29) % 70)}%`, top: `${20 + ((index * 37) % 64)}%`, backgroundColor: ticket.priority === "urgent" ? "#e11d48" : ticket.priority === "high" ? "#f97316" : "#0e7490" }}>{ticket.id}</button>)}</div><div className="mt-3 flex flex-wrap gap-2 text-xs text-tide-600"><span className="chip border-rose-200 bg-rose-50 text-rose-700">urgent/high</span><span className="chip border-sky-200 bg-sky-50 text-sky-700">medium/low</span><span>{tickets.length} reports · {open.length} active · {tickets.filter((ticket) => ticket.location).length} with location</span></div></section>}
    {mode === "risk" && <div className="grid gap-4 md:grid-cols-2">{(urgent.length ? urgent : open).slice(0, 8).map((ticket) => { const score = Math.min(99, 40 + (ticket.priority === "urgent" ? 48 : ticket.priority === "high" ? 32 : 14) + (slaState(ticket).breached ? 11 : 0) + Math.min(ticket.cosigns, 5)); return <article key={ticket.id} className="well p-5"><div className="flex items-center justify-between"><Chip tone={ticket.priority}>{ticket.priority}</Chip><span className="font-mono text-xs text-tide-500">risk {score}</span></div><h2 className="mt-3 font-display text-xl font-semibold text-tide-950">{ticket.category} · Ward {ticket.ward}</h2><p className="mt-1 text-sm text-tide-600">{ticket.location || "Location pending"}</p><Meter pct={score} tone={score > 75 ? "rose" : "saffron"} label={`${score}% attention score · ${slaState(ticket).label}`} /></article>; })}</div>}
    {mode === "insights" && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Total reports", tickets.length], ["Active reports", open.length], ["Urgent/high", urgent.length], ["Within SLA", `${tickets.length ? Math.round((onTime / tickets.length) * 100) : 0}%`]].map(([label, value]) => <article key={label} className="well p-5"><p className="label">{label}</p><p className="mt-3 text-4xl font-black text-tide-950">{value}</p></article>)}<section className="well sm:col-span-2 lg:col-span-4 p-5"><h2 className="font-display text-xl font-semibold text-tide-950">Category mix</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => { const count = tickets.filter((ticket) => ticket.category === category).length; return <Meter key={category} pct={tickets.length ? (count / tickets.length) * 100 : 0} label={`${category} · ${count}`} />; })}</div></section></div>}
    {mode === "channels" && <div className="grid gap-4 md:grid-cols-3">{[{ title: "Citizen text", body: "Report a pothole, drain, waste, water, streetlight or sewage issue with a location.", href: "/report" }, { title: "Evidence photos", body: "Attach a photo for severity and trust analysis before the report enters the queue.", href: "/report" }, { title: "Operations adapters", body: "The server app accepts monitored WhatsApp, X and news signal routes and normalizes them into the same complaint model.", href: `${import.meta.env.VITE_APP_URL ?? ""}/channels` }].map((channel) => <article key={channel.title} className="well p-5"><Chip tone="medium">intake</Chip><h2 className="mt-3 font-display text-xl font-semibold text-tide-950">{channel.title}</h2><p className="mt-2 text-sm leading-relaxed text-tide-600">{channel.body}</p><a href={channel.href} className="mt-5 inline-block text-sm font-semibold text-saffron-700 hover:underline">Open channel →</a></article>)}</div>}
    <div className="mt-8"><Link to="/report" className="rounded-xl bg-tide-950 px-5 py-3 text-sm font-semibold text-white">Report an issue</Link></div>
  </div>;
}